configs:
  T_SQUARE_TO_AXIS:
    title: T‑квадрат к {axis_dat} — {tr_gl}
    lead: 'Напряжение: {tr_ru} в квадрате к {a1_ru} и {a2_ru} ({axis_label}). Две
      «ноги» требуют действия; энергия ищет выход.'
    advice: Сфокусируйтесь на одной точке приложения силы; не распыляйтесь. Начните
      с участка дома {tr_house}.
  KITE_TO_AXIS:
    title: Парус к {axis_dat} — {tr_gl}
    lead: 'Поддержка: {tr_ru} держит трин к {tri_ru} и секстиль к {sex_ru} — «выход»
      есть, но его надо запустить.'
    advice: Сделайте первый шаг через зону трине; секстиль намекает на шаги с вашей
      стороны.
  GRAND_CROSS_AXES:
    title: Большой крест к осям — {lead}
    lead: 'Крест напряжения: включены обе оси (ASC/DSC и MC/IC). Вызов — {work_verb}
      между полюсами; держать баланс и ритм.'
    advice: Дробите задачи; синхронизируйте роли; опирайтесь на дом {anchor_house}.
  GRAND_TRINE_TRANSITS:
    title: Большой трин — {p1_gl} △ {p2_gl} △ {p3_gl}
    lead: 'Плавный поток: треугольная поддержка между {p1_ru}, {p2_ru} и {p3_ru}.
      Легче собирать результат, если задать направление.'
    advice: Определите вектор (дом {anchor_house}), уберите лишнее, закрепляйте успех
      практикой.
domains:
  health:
    T_SQUARE_TO_AXIS: В здоровье — избегайте перегрузок; «снятие напряжения» через
      дозированную активность в зоне дома {tr_house}.
    KITE_TO_AXIS: В здоровье — мягкий «выход» через режим/сон/дыхание; трин — естественный
      путь, по секстилю — сделать шаг.
    GRAND_CROSS_AXES: В здоровье — аккуратность при повышенных нагрузках; дробите
      активность; сон — в приоритете.
    GRAND_TRINE_TRANSITS: В здоровье — неспеша восстанавливайте привычки; не теряйте
      дисциплину, пока всё «само идёт».
  work:
    T_SQUARE_TO_AXIS: В работе — сузить фронт; выбрать ключевую связку и додавить.
      Не хватайтесь за всё сразу.
    KITE_TO_AXIS: В работе — используйте союз/связку (трин); по секстилю — сделайте
      первый шаг.
    GRAND_CROSS_AXES: В работе — лавировать между домом и задачами; планировать «тихие
      окна» для глубокой работы.
    GRAND_TRINE_TRANSITS: 'В работе — выстраивайте поток: автоматизируйте рутину и
      укрепляйте то, что уже получается.'
  finance:
    T_SQUARE_TO_AXIS: Финансы — не дергаться за всё сразу; один канал в фокусе. Накачайте
      «узкий» дом {tr_house}, уберите утечки.
    KITE_TO_AXIS: 'Финансы — используйте естественную поддержку (трин): то, что уже
      получается. По секстилю — сделайте первый шаг.'
    GRAND_CROSS_AXES: Финансы — бюджет/обязательства и домашние расходы могут тянуть
      в разные стороны; дробите платежи; график финансовых действий.
    GRAND_TRINE_TRANSITS: 'Финансы — «время собирать»: закрепляйте успешные схемы,
      не разбрасывайтесь, автоматизируйте повторяющееся.'
  relationships:
    T_SQUARE_TO_AXIS: Отношения — не срывайтесь на обе «ноги» конфликта; выберите
      один фокус разговора, остальное отложите.
    KITE_TO_AXIS: Отношения — используйте сильную сторону трина (зона согласия); по
      секстилю — сделайте первый шаг к сближению.
    GRAND_CROSS_AXES: Отношения — лавировать между «я/мы» и «дом/работа»; договариваться
      заранее, выделять «тихие окна» для пары.
    GRAND_TRINE_TRANSITS: Отношения — мягко укрепляйте то, что получается, без насилия
      над процессом; внимание к регулярности, не к новизне.
